independent_vars:
- week
sample_params:
  draws: 1000
variable_params:
  intercept:
    dist: Normal
    params:
      mu: 0.09052028965984911
      sigma: 0.00998416579006974
  lambda_val:
    dist: HalfNormal
    params:
      sigma: 0.8406296371105827
